Lecture 20
UofTCoders/rcourse pull request #171
Opened 2017-10-30 23:07 UTC by linamnt

This was a hard lecture to make since I feel like I only know some of this stuff through second-hand experience rather than loads of personal experience with publishing/writing. Hard to know also if the content is covering what you guys had in mind for this lecture too...so I'll definitely need your comments and help with this one :)

2017-11-01 02:11 UTC, joelostblom reviewed
This is difficult for me too... Not much first hand experience. I guess one thing that I would add is to be realistic where you want to publish and that your supervisor probably wants to go as high as possible, which might hurt you in the form of a very long process where you get the manuscript back multiple times and needs to do extensive revisions. It is great to get good feedback from top reviewers, but it not a good idea to try to oversell your work, it's a balance, but try to stick truthfully to where you think your worbring all k belongs (although this is hard to know in the beginning). Ok, a little rambley, but something about the balance of where to publish.

2017-11-01 02:11 UTC, joelostblom commented on lec20-publishing.Rmd
>  title: "Preparing a scientific item for academic publishing"
add yourself as author

2017-11-01 02:11 UTC, joelostblom commented on lec20-publishing.Rmd
> +>     - Moving away from impact factors (10 min)
yay!

2017-11-01 02:11 UTC, joelostblom commented on lec20-publishing.Rmd
> +and software creators compared to ?
unfinished sentence

2017-11-01 02:11 UTC, joelostblom commented on lec20-publishing.Rmd
> +- Define your terms: don't use acronyms without first defining them,
no comma at the EOL

2017-11-03 18:20 UTC, lwjohnst86 requested changes
Well done! I've added some comments, but most are typos/spelling.

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +>     - How to credit data and software creators? 10 min)
forgot starting `(`

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +course](https://cbahlai.github.io/rqm-template/lessons/week3/)*
This can be put on the bottom of the lesson. Saying something like "This lesson has been adapted from ...".

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +Here are some common types of contributions:
Might need to mention that *usually* authorship requires having at least two of these plus having read the manuscript and approving it's content.

Maybe link to this [page](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html). Many biomedical journals use this recommendation to define "authorship".

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +**Tip:** Have discussions about authorship early! If you're concerned
I might not even say this is a "tip", this should be a requirement! Or at least strongly strongly encouraged.

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +As researchers in all sorts of fields begin to fruther embrace scripting and
s/fruther/further

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +#### The Scientific Life Cycle
Any reason why this is four `#`?

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +Broadly speaking, the life cycle of scientific publications entailst the following:
s/entailst/entails/

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +a research article, review or body of scientific work that has yet to be published in a journal.
`s/review or body/review, or body/` needs the Oxford comma

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +be more common in basic science that has clinical/translational implications.
maybe "...basic science that has potential clinical..."

2017-11-03 18:20 UTC, lwjohnst86 commented on lec20-publishing.Rmd
> +### Journal Specifications
This is useful to include in the material, but you may not need to talk about this in much detail, if at all.

2017-11-09 23:56 UTC, lwjohnst86 approved these changes

2017-11-21 17:27 UTC, merged